// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUiJ6eGKFpwm00GmT-MFCh-yjdVBMAfwE',
    appId: '1:759254320988:web:0f7d0c068eab24e045a399',
    messagingSenderId: '759254320988',
    projectId: 'event-planer-85510',
    authDomain: 'event-planer-85510.firebaseapp.com',
    storageBucket: 'event-planer-85510.firebasestorage.app',
    measurementId: 'G-K41G9EWJ85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiwaFf3jHzKM-q51vUxQLNJbGyPitY5A',
    appId: '1:759254320988:android:f2d4e9c03b5306a845a399',
    messagingSenderId: '759254320988',
    projectId: 'event-planer-85510',
    storageBucket: 'event-planer-85510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZd8qh06kT1yufc7hg6BVLZ3AXzgEhaw',
    appId: '1:759254320988:ios:88db0ed05fe2fb7645a399',
    messagingSenderId: '759254320988',
    projectId: 'event-planer-85510',
    storageBucket: 'event-planer-85510.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLZd8qh06kT1yufc7hg6BVLZ3AXzgEhaw',
    appId: '1:759254320988:ios:88db0ed05fe2fb7645a399',
    messagingSenderId: '759254320988',
    projectId: 'event-planer-85510',
    storageBucket: 'event-planer-85510.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUiJ6eGKFpwm00GmT-MFCh-yjdVBMAfwE',
    appId: '1:759254320988:web:a7221c1a0e0fae3545a399',
    messagingSenderId: '759254320988',
    projectId: 'event-planer-85510',
    authDomain: 'event-planer-85510.firebaseapp.com',
    storageBucket: 'event-planer-85510.firebasestorage.app',
    measurementId: 'G-QQVD18MFCB',
  );

}